trigger:
  batch: true
  branches:
    include:
    - dotnet/main
    - dotnet/release/*

pr:
  branches:
    include:
    - dotnet/main
    - dotnet/release/*

variables:
  - template: /eng/common-variables.yml
  - template: /eng/common/templates/variables/pool-providers.yml
  - name: CheckNuGetSizesScript
    value: >-
      $nupkgs_large=(Get-ChildItem artifacts/packages/$(_BuildConfig)/Shipping -recurse -include "*.nupkg" | Select-Object Name,Length | Where-Object { $_.Length -gt 250*1MB });
      if ($nupkgs_large.Length -gt 0) { Write-Error "NuGet size exceeds 250MiB: $($nupkgs_large | Format-Table | Out-String)"; exit 1 }

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      enablePublishBuildArtifacts: true
      enablePublishBuildAssets: true
      publishingVersion: 4
      enableMicrobuild: true
      jobs:

      ############ LINUX BUILD ############
      - job: Build_Linux
        enablePublishing: true
        displayName: Linux
        timeoutInMinutes: 480
        strategy:
          matrix:
            x64:
              assetManifestOS: linux
              assetManifestPlatform: x64
              imagename: mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-cross-amd64
              archflag: /p:ArchGroup=x64 /p:TargetArchitecture=x64
            arm64:
              assetManifestOS: linux
              assetManifestPlatform: arm64
              imagename: mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-cross-amd64
              archflag: /p:ArchGroup=arm64 /p:TargetArchitecture=arm64
            x64_musl:
              assetManifestOS: linux-musl
              assetManifestPlatform: x64
              imagename: mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-cross-amd64
              archflag: /p:ArchGroup=x64 /p:TargetArchitecture=x64
            arm64_musl:
              assetManifestOS: linux-musl
              assetManifestPlatform: arm64
              imagename: mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-cross-amd64
              archflag: /p:ArchGroup=arm64 /p:TargetArchitecture=arm64
        pool:
          name: $(DncEngPublicBuildPool)
          demands: ImageOverride -equals build.azurelinux.3.amd64.open
        container:
          image: $(imagename)
        preSteps:
        - checkout: self
          submodules: recursive

        steps:
        - bash: |
            ./build.sh --ci --pack --publish --configuration $(_BuildConfig) $(_InternalBuildArgs) /p:AssetManifestOS=$(assetManifestOS) $(archflag) /p:PlatformName=$(assetManifestPlatform) /p:PackageRID=$(assetManifestOS)-$(assetManifestPlatform) /p:RestoreUsingNuGetTargets=false
          displayName: 'Build and Publish'

        - powershell: $(CheckNuGetSizesScript)
          displayName: Check NuGet sizes
          continueOnError: true # TODO: our packages exceed the size limits, but we don't want to fail the build for now

      ############ MACOS BUILD ############
      - job: Build_macOS
        enablePublishing: true
        displayName: macOS
        timeoutInMinutes: 480
        strategy:
          matrix:
            x64:
              assetManifestOS: osx
              assetManifestPlatform: x64
              archflag: /p:ArchGroup=x64 /p:TargetArchitecture=x64
            arm64:
              assetManifestOS: osx
              assetManifestPlatform: arm64
              archflag: /p:ArchGroup=arm64 /p:TargetArchitecture=arm64
        pool:
          vmImage: macos-14
        preSteps:
        - checkout: self
          submodules: recursive

        steps:
        - bash: |
            ./build.sh --ci --pack --publish --configuration $(_BuildConfig) $(archflag) $(_InternalBuildArgs) /p:RestoreUsingNuGetTargets=false
          displayName: 'Build and Publish'

        - powershell: $(CheckNuGetSizesScript)
          displayName: Check NuGet sizes
          continueOnError: true # TODO: our packages exceed the size limits, but we don't want to fail the build for now

      ############ WINDOWS BUILD ############
      - job: Build_Windows
        enablePublishing: true
        displayName: Windows
        timeoutInMinutes: 480
        strategy:
          matrix:
            x64:
              assetManifestOS: win
              assetManifestPlatform: x64
              archflag: /p:ArchGroup=x64 /p:TargetArchitecture=x64
            arm64:
              assetManifestOS: win
              assetManifestPlatform: arm64
              archflag: /p:ArchGroup=arm64 /p:TargetArchitecture=arm64
        pool:
          name: $(DncEngPublicBuildPool)
          demands: ImageOverride -equals 1es-windows-2022-open
        preSteps:
        - checkout: self
          submodules: recursive

        steps:

        - powershell: |
            Invoke-WebRequest "https://netcorenativeassets.blob.core.windows.net/resource-packages/external/windows/make/make-4.4.1-2-x86_64.zip" -OutFile C:\make.zip
            Invoke-WebRequest "https://netcorenativeassets.blob.core.windows.net/resource-packages/external/windows/diffutils/diffutils-3.12-1-x86_64.zip" -OutFile C:\diffutils.zip
            Expand-Archive -LiteralPath C:\make.zip -DestinationPath C:\
            Expand-Archive -LiteralPath C:\diffutils.zip -DestinationPath C:\
            cp C:\make-4.4.1-2-x86_64\usr\bin\make.exe C:\msys64\usr\bin\
            cp C:\diffutils-3.12-1-x86_64\usr\bin\diff.exe C:\msys64\usr\bin\
          displayName: Install make and diff

        - script: |
            .\build.cmd -ci -pack -publish -sign -configuration $(_BuildConfig) $(archflag) /p:PackageRID=$(assetManifestOS)-$(assetManifestPlatform) /p:AssetManifestOS=$(assetManifestOS) /p:PlatformName=$(assetManifestPlatform) /p:MsysDir=c:\msys64 /p:SignCheckExclusionsFile='$(Build.SourcesDirectory)/eng/SignCheckExclusionsFile.txt' $(_InternalBuildArgs)
          displayName: 'Build and Publish'

        - powershell: $(CheckNuGetSizesScript)
          displayName: Check NuGet sizes
          continueOnError: true # TODO: our packages exceed the size limits, but we don't want to fail the build for now
